# Generated by Django 6.1.1 on 2026-10-04 10:28

from typing import ClassVar

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies: ClassVar[list] = []

    operations: ClassVar[list] = [
        migrations.CreateModel(
            name="IndexStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("last_drain_at", models.DateTimeField(blank=True, null=True)),
                ("last_rebuild_at", models.DateTimeField(blank=True, null=True)),
                ("last_error", models.TextField(blank=True, default="")),
                ("last_error_at", models.DateTimeField(blank=True, null=True)),
                (
                    "last_error_job",
                    models.CharField(blank=True, default="", max_length=16),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PendingChange",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("document_id", models.CharField(max_length=512, unique=True)),
                ("generation", models.PositiveIntegerField(default=1)),
                ("queued_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ("id",),
            },
        ),
    ]
