# Generated by Django 6.1.1 on 2026-10-02 14:45

from typing import ClassVar

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies: ClassVar[list] = [
        ("catalog", "0001_initial"),
    ]

    operations: ClassVar[list] = [
        migrations.CreateModel(
            name="RegisteredRepository",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source_id",
                    models.CharField(
                        help_text="References a source id declared in atlas.ingestion plugin config",
                        max_length=255,
                    ),
                ),
                (
                    "path",
                    models.CharField(
                        help_text="Repository path relative to the source's baseUrl",
                        max_length=1024,
                    ),
                ),
                ("default_branch", models.CharField(default="main", max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["source_id", "path"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("source_id", "path"),
                        name="unique_registered_repository_source_path",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="IngestionIssue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("repo_full_name", models.CharField(max_length=255)),
                ("path", models.CharField(blank=True, max_length=1024)),
                ("message", models.TextField()),
                ("is_active", models.BooleanField(default=True)),
                ("first_seen", models.DateTimeField(auto_now_add=True)),
                ("last_seen", models.DateTimeField(auto_now=True)),
                (
                    "repository",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ingestion_issues",
                        to="ingestion.registeredrepository",
                    ),
                ),
            ],
            options={
                "ordering": ["-last_seen"],
            },
        ),
        migrations.CreateModel(
            name="EntityClaim",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "entity",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ingestion_claim",
                        to="catalog.catalogentity",
                    ),
                ),
                (
                    "repository",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="claims",
                        to="ingestion.registeredrepository",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ConflictRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("repo_full_name", models.CharField(max_length=255)),
                ("kind", models.CharField(max_length=32)),
                ("namespace", models.CharField(default="default", max_length=255)),
                ("name", models.CharField(max_length=255)),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("manual_entity", "Claimed by a manual entity"),
                            ("other_repository", "Claimed by a different repository"),
                            ("removed_entity", "Claimed by a removed entity"),
                        ],
                        max_length=32,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("first_seen", models.DateTimeField(auto_now_add=True)),
                ("last_seen", models.DateTimeField(auto_now=True)),
                (
                    "repository",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="conflict_records",
                        to="ingestion.registeredrepository",
                    ),
                ),
            ],
            options={
                "ordering": ["-last_seen"],
            },
        ),
    ]
