# Generated by Django 5.2.17 on 2026-08-24 13:53

from typing import ClassVar

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies: ClassVar[list] = [
        ("ingestion", "0001_initial"),
    ]

    operations: ClassVar[list] = [
        migrations.CreateModel(
            name="ConflictRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("repo_full_name", models.CharField(max_length=255)),
                ("kind", models.CharField(max_length=32)),
                ("namespace", models.CharField(default="default", max_length=255)),
                ("name", models.CharField(max_length=255)),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("manual_entity", "Claimed by a manual entity"),
                            ("other_repository", "Claimed by a different repository"),
                        ],
                        max_length=32,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("first_seen", models.DateTimeField(auto_now_add=True)),
                ("last_seen", models.DateTimeField(auto_now=True)),
                (
                    "repository",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="conflict_records",
                        to="ingestion.registeredrepository",
                    ),
                ),
            ],
            options={
                "ordering": ["-last_seen"],
            },
        ),
    ]
