# Generated by Django 6.1 on 2026-09-10 05:44

from typing import ClassVar

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies: ClassVar[list] = [
        ("ingestion", "0002_conflictrecord"),
    ]

    operations: ClassVar[list] = [
        migrations.AlterField(
            model_name="conflictrecord",
            name="reason",
            field=models.CharField(
                choices=[
                    ("manual_entity", "Claimed by a manual entity"),
                    ("other_repository", "Claimed by a different repository"),
                    ("removed_entity", "Claimed by a removed entity"),
                ],
                max_length=32,
            ),
        ),
    ]
