# Generated by Django 6.1 on 2026-09-23

from typing import ClassVar

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies: ClassVar[list] = [
        ("ingestion", "0003_alter_conflictrecord_reason"),
    ]

    operations: ClassVar[list] = [
        migrations.AlterModelOptions(
            name="registeredrepository",
            options={"ordering": ["source_id", "path"]},
        ),
        migrations.RemoveField(
            model_name="registeredrepository",
            name="access_token",
        ),
        migrations.RemoveField(
            model_name="registeredrepository",
            name="full_name",
        ),
        migrations.AddField(
            model_name="registeredrepository",
            name="path",
            field=models.CharField(
                default=None,
                help_text="Repository path relative to the source's baseUrl",
                max_length=1024,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="registeredrepository",
            name="source_id",
            field=models.CharField(
                default=None,
                help_text="References a source id declared in atlas.ingestion plugin config",
                max_length=255,
            ),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name="registeredrepository",
            constraint=models.UniqueConstraint(
                fields=("source_id", "path"),
                name="unique_registered_repository_source_path",
            ),
        ),
    ]
