# Generated by Django 6.1 on 2026-09-25 12:47

from typing import ClassVar

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies: ClassVar[list] = [
        ("ingestion", "0004_registeredrepository_source_id_path"),
    ]

    operations: ClassVar[list] = [
        migrations.CreateModel(
            name="IngestionIssue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("repo_full_name", models.CharField(max_length=255)),
                ("path", models.CharField(blank=True, max_length=1024)),
                ("message", models.TextField()),
                ("is_active", models.BooleanField(default=True)),
                ("first_seen", models.DateTimeField(auto_now_add=True)),
                ("last_seen", models.DateTimeField(auto_now=True)),
                (
                    "repository",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ingestion_issues",
                        to="ingestion.registeredrepository",
                    ),
                ),
            ],
            options={
                "ordering": ["-last_seen"],
            },
        ),
    ]
