// GENERATED by `atlas-compose generate` from atlas.default@2026.09's lock file. Do not edit by hand — regenerate from the manifest/lock instead.
import { standardCatalogPlugin } from '@atlas/plugin-standard-catalog'
import { apisPlugin } from '@atlas/plugin-apis'
import { c4Plugin } from '@atlas/plugin-c4'
import { databaseSchemaPlugin } from '@atlas/plugin-database-schema'
import { flowsPlugin } from '@atlas/plugin-flows'
import { searchPlugin } from '@atlas/plugin-search'
import { composeFrontendPlugins } from '@atlas/plugin-api'
import { corePlugin } from './core'

export const installedFrontendPlugins = [
  standardCatalogPlugin,
  apisPlugin,
  c4Plugin,
  databaseSchemaPlugin,
  flowsPlugin,
  searchPlugin,
  corePlugin,
] as const

export const composedContributions = composeFrontendPlugins(installedFrontendPlugins)

export const authenticationBootstrap = {
  "providers": [
    {
      "id": "atlas.auth.local",
      "contractVersion": "atlas.auth.providers.v1",
      "flowKind": "credentials",
      "presentation": {
        "displayName": "Username and password",
        "credentialFields": [
          {
            "id": "username",
            "label": "Username",
            "kind": "text",
            "autocomplete": "username"
          },
          {
            "id": "password",
            "label": "Password",
            "kind": "secret",
            "autocomplete": "current-password"
          }
        ]
      },
      "remoteLogout": "unsupported",
      "isDefault": true,
      "signupOpen": false
    }
  ],
  "defaultProviderId": "atlas.auth.local",
  "providerChoiceUrl": "/login?choose-provider=1"
} as const
