# Generated by Django 6.1 on 2026-09-01 16:01

from typing import ClassVar

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies: ClassVar[list] = [
        ("catalog", "0013_entity_audit_record"),
    ]

    operations: ClassVar[list] = [
        migrations.CreateModel(
            name="DatabaseSchema",
            fields=[
                (
                    "entity",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="database_schema",
                        serialize=False,
                        to="catalog.catalogentity",
                    ),
                ),
                (
                    "dialect",
                    models.CharField(
                        choices=[("postgresql", "PostgreSQL")],
                        default="postgresql",
                        max_length=32,
                    ),
                ),
                ("source_sql", models.TextField(blank=True)),
                ("parsed_schema", models.JSONField(blank=True, default=dict)),
                (
                    "parse_status",
                    models.CharField(
                        choices=[("ok", "Ok"), ("failed", "Failed")],
                        default="ok",
                        max_length=16,
                    ),
                ),
            ],
        ),
    ]
