# Generated by Django 6.1 on 2026-09-04 04:29

from typing import ClassVar

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies: ClassVar[list] = [
        ("database_schema_plugin", "0001_initial"),
    ]

    operations: ClassVar[list] = [
        migrations.AlterField(
            model_name="databaseschema",
            name="dialect",
            field=models.CharField(
                choices=[
                    ("postgresql", "PostgreSQL"),
                    ("mysql", "MySQL"),
                    ("mssql", "MS SQL"),
                ],
                default="postgresql",
                max_length=32,
            ),
        ),
    ]
