# Generated by Django 6.1 on 2026-09-05 09:03

import uuid
from typing import ClassVar

import django.contrib.postgres.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies: ClassVar[list] = [
        ("apis_plugin", "0001_initial"),
        ("catalog", "0015_apidetails_endpoints_sync_failed_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations: ClassVar[list] = [
        migrations.CreateModel(
            name="ApiOperation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("channel_address", models.CharField(max_length=2048)),
                ("channel_protocol", models.CharField(blank=True, max_length=64)),
                (
                    "direction",
                    models.CharField(
                        choices=[("send", "Send"), ("receive", "Receive")],
                        max_length=16,
                    ),
                ),
                ("operation_key", models.CharField(max_length=512)),
                ("operation_id", models.CharField(blank=True, max_length=255)),
                ("summary", models.CharField(blank=True, max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "tags",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=100),
                        blank=True,
                        default=list,
                    ),
                ),
                ("message", models.JSONField(blank=True, default=list)),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("removed", "Removed")],
                        default="active",
                        max_length=16,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "api",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="operations",
                        to="catalog.catalogentity",
                    ),
                ),
            ],
            options={
                "ordering": ["channel_address", "operation_key"],
            },
        ),
        migrations.CreateModel(
            name="ServiceOperationUsage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("publisher", "Publisher"),
                            ("subscriber", "Subscriber"),
                        ],
                        max_length=16,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "operation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="service_usages",
                        to="apis_plugin.apioperation",
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="operation_usages",
                        to="catalog.catalogentity",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="apioperation",
            constraint=models.UniqueConstraint(
                models.F("api"),
                models.F("operation_key"),
                name="apioperation_unique_api_operation_key",
            ),
        ),
        migrations.AddConstraint(
            model_name="serviceoperationusage",
            constraint=models.UniqueConstraint(
                models.F("operation"),
                models.F("service"),
                models.F("role"),
                name="serviceoperationusage_unique_operation_service_role",
            ),
        ),
    ]
