# Generated by Django 6.1 on 2026-09-10 07:23

from typing import ClassVar

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies: ClassVar[list] = [
        ("apis_plugin", "0002_apioperation_serviceoperationusage_and_more"),
    ]

    operations: ClassVar[list] = [
        migrations.AddField(
            model_name="apioperation",
            name="deprecated",
            field=models.BooleanField(default=False),
        ),
    ]
