# Generated by Django 6.1 on 2026-09-17 13:17

from typing import ClassVar

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies: ClassVar[list] = [
        ("apis_plugin", "0003_apioperation_deprecated"),
    ]

    operations: ClassVar[list] = [
        migrations.AddField(
            model_name="apioperation",
            name="external_docs",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
