# Generated by Django 6.1 on 2026-09-17 16:30

from typing import ClassVar

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies: ClassVar[list] = [
        ("apis_plugin", "0004_apioperation_external_docs"),
    ]

    operations: ClassVar[list] = [
        migrations.AddField(
            model_name="apiendpoint",
            name="external_docs",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="apiendpoint",
            name="security",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
