# Generated by Django 6.1.1 on 2026-10-01 23:51

from typing import ClassVar

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies: ClassVar[list] = [
        ("apis_plugin", "0005_apiendpoint_external_docs_apiendpoint_security"),
    ]

    operations: ClassVar[list] = [
        migrations.AddField(
            model_name="serviceendpointusage",
            name="origin",
            field=models.CharField(
                choices=[("manual", "Manual"), ("yaml", "YAML")],
                default="manual",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="serviceendpointusage",
            name="source",
            field=models.CharField(
                choices=[("ui", "UI"), ("mcp", "MCP")], default="ui", max_length=16
            ),
        ),
        migrations.AddField(
            model_name="serviceoperationusage",
            name="origin",
            field=models.CharField(
                choices=[("manual", "Manual"), ("yaml", "YAML")],
                default="manual",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="serviceoperationusage",
            name="source",
            field=models.CharField(
                choices=[("ui", "UI"), ("mcp", "MCP")], default="ui", max_length=16
            ),
        ),
    ]
