# Generated by Django 6.1.1 on 2026-10-02 14:45

import uuid
from typing import ClassVar

import django.contrib.postgres.fields
import django.db.models.deletion
import django.db.models.functions.text
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies: ClassVar[list] = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations: ClassVar[list] = [
        migrations.CreateModel(
            name="CatalogEntity",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("system", "System"),
                            ("component", "Component"),
                            ("resource", "Resource"),
                            ("api", "API"),
                            ("group", "Group"),
                            ("user", "User"),
                        ],
                        max_length=16,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "namespace",
                    models.CharField(default="default", max_length=255),
                ),
                ("title", models.CharField(blank=True, max_length=255)),
                ("description", models.TextField(blank=True)),
                ("documentation", models.TextField(blank=True)),
                ("labels", models.JSONField(blank=True, default=dict)),
                (
                    "tags",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=100),
                        blank=True,
                        default=list,
                    ),
                ),
                ("links", models.JSONField(blank=True, default=list)),
                (
                    "source_kind",
                    models.CharField(
                        choices=[("manual", "Manual"), ("yaml", "YAML")],
                        default="manual",
                        max_length=16,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("removed", "Removed")],
                        default="active",
                        max_length=16,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="owned_entities",
                        to="catalog.catalogentity",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="AuthenticationPolicyState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("digest", models.CharField(max_length=64)),
                ("generation", models.PositiveBigIntegerField(default=1)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="AuthenticationRateLimit",
            fields=[
                (
                    "key_hash",
                    models.CharField(
                        max_length=64, primary_key=True, serialize=False
                    ),
                ),
                ("scope", models.CharField(db_index=True, max_length=32)),
                ("window_started_at", models.DateTimeField()),
                ("count", models.PositiveIntegerField(default=0)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="AuthenticationSecurityEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("category", models.CharField(max_length=64)),
                (
                    "stage",
                    models.CharField(default="provisioning", max_length=64),
                ),
                ("provider_id", models.CharField(max_length=128)),
                ("source_id", models.CharField(max_length=512)),
                (
                    "correlation_id",
                    models.CharField(db_index=True, max_length=64),
                ),
                (
                    "principal_id",
                    models.PositiveBigIntegerField(blank=True, null=True),
                ),
                ("details", models.JSONField(blank=True, default=dict)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ("-timestamp",),
            },
        ),
        migrations.CreateModel(
            name="CatalogHomeSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("about_markdown", models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "color",
                    models.CharField(
                        choices=[
                            ("gray", "gray"),
                            ("red", "red"),
                            ("orange", "orange"),
                            ("yellow", "yellow"),
                            ("green", "green"),
                            ("blue", "blue"),
                            ("purple", "purple"),
                            ("pink", "pink"),
                        ],
                        default="gray",
                        max_length=32,
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="AccountAccess",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("read_only", models.BooleanField(default=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "account",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="account_access",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AccountAccessAuditRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("target_id", models.PositiveBigIntegerField(db_index=True)),
                ("target_username", models.CharField(max_length=150)),
                (
                    "action",
                    models.CharField(
                        choices=[("create", "Create"), ("update", "Update")],
                        max_length=16,
                    ),
                ),
                ("old_read_only", models.BooleanField(null=True)),
                ("new_read_only", models.BooleanField(null=True)),
                ("reason", models.TextField(blank=True, default="")),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "operator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="GroupDetails",
            fields=[
                (
                    "entity",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="group_details",
                        serialize=False,
                        to="catalog.catalogentity",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("team", "Team"),
                            ("business-unit", "Business unit"),
                            ("product-area", "Product area"),
                            ("root", "Root"),
                        ],
                        max_length=32,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SystemDetails",
            fields=[
                (
                    "entity",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="system_details",
                        serialize=False,
                        to="catalog.catalogentity",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ArchitectureRelationship",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(max_length=255)),
                ("technology", models.CharField(blank=True, max_length=255)),
                (
                    "interaction_kind",
                    models.CharField(
                        choices=[
                            ("synchronous", "Synchronous"),
                            ("asynchronous", "Asynchronous"),
                            ("data-access", "Data access"),
                            ("manual", "Manual"),
                        ],
                        default="manual",
                        max_length=16,
                    ),
                ),
                (
                    "tags",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=100),
                        blank=True,
                        default=list,
                    ),
                ),
                (
                    "origin",
                    models.CharField(
                        choices=[("manual", "Manual"), ("yaml", "YAML")],
                        default="manual",
                        max_length=16,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="architecture_relationships_as_source",
                        to="catalog.catalogentity",
                    ),
                ),
                (
                    "target",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="architecture_relationships_as_target",
                        to="catalog.catalogentity",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AuthenticationAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("provider_id", models.CharField(max_length=128)),
                ("source_id", models.CharField(max_length=512)),
                (
                    "state_digest",
                    models.CharField(max_length=64, null=True, unique=True),
                ),
                ("browser_session_digest", models.CharField(max_length=64)),
                ("return_url", models.TextField()),
                ("correlation_id", models.UUIDField()),
                (
                    "policy_generation",
                    models.PositiveBigIntegerField(default=1),
                ),
                (
                    "source_generation",
                    models.PositiveBigIntegerField(default=0),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
                ("consumed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["provider_id", "expires_at"],
                        name="catalog_auth_attempt_expiry",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="AuthenticationPrincipalState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "revocation_generation",
                    models.PositiveBigIntegerField(default=0),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="authentication_state",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AuthenticationSourceBinding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("provider_id", models.CharField(max_length=128)),
                ("source_id", models.CharField(max_length=512)),
                ("configuration_fingerprint", models.CharField(max_length=255)),
                (
                    "lock_digest",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("generation", models.PositiveBigIntegerField(default=1)),
                ("activated_at", models.DateTimeField(auto_now_add=True)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("provider_id", "source_id"),
                        name="catalog_unique_auth_source_binding",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="EntityAuditRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("entity_id", models.UUIDField(db_index=True)),
                ("kind", models.CharField(max_length=32)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("create", "Create"),
                            ("update", "Update"),
                            ("delete", "Delete"),
                            ("remove", "Remove"),
                            ("revive", "Revive"),
                            ("purge", "Purge"),
                        ],
                        max_length=16,
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("diff", models.JSONField(blank=True, default=dict)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="ExternalIdentityLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("provider_id", models.CharField(max_length=64)),
                (
                    "source_id",
                    models.CharField(blank=True, default="", max_length=512),
                ),
                ("external_subject", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                (
                    "revocation_generation",
                    models.PositiveBigIntegerField(default=0),
                ),
                (
                    "last_applied_generation",
                    models.PositiveBigIntegerField(default=0),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="external_identity_links",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Flow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("documentation", models.TextField(blank=True)),
                ("steps", models.JSONField(blank=True, default=list)),
                ("autolayout_enabled", models.BooleanField(default=True)),
                (
                    "layout_direction",
                    models.CharField(
                        choices=[
                            ("LAYOUT_LEFT_RIGHT", "Left-right"),
                            ("LAYOUT_TOP_DOWN", "Top-down"),
                        ],
                        default="LAYOUT_LEFT_RIGHT",
                        max_length=32,
                    ),
                ),
                (
                    "layout_engine",
                    models.CharField(
                        choices=[("dagre", "Dagre"), ("elk", "ELK.js")],
                        default="dagre",
                        max_length=32,
                    ),
                ),
                (
                    "system",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="flows",
                        to="catalog.catalogentity",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="MembershipGrantAuditRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("grant_id", models.PositiveBigIntegerField(db_index=True)),
                ("group_id", models.UUIDField(db_index=True)),
                ("actor_id", models.UUIDField(db_index=True)),
                (
                    "identity_link_id",
                    models.PositiveBigIntegerField(blank=True, null=True),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("classify_manual", "Classify as manual"),
                            ("transfer_provider", "Transfer to provider"),
                        ],
                        max_length=32,
                    ),
                ),
                ("reason", models.TextField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("details", models.JSONField(blank=True, default=dict)),
                (
                    "operator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-timestamp",),
            },
        ),
        migrations.CreateModel(
            name="PersonalAccessToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("prefix", models.CharField(db_index=True, max_length=8)),
                ("token_hash", models.CharField(max_length=64, unique=True)),
                ("scopes", models.JSONField(blank=True, default=list)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                ("last_used_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="personal_access_tokens",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProvisioningAuditRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("action", models.CharField(max_length=64)),
                ("provider_id", models.CharField(max_length=128)),
                ("source_id", models.CharField(max_length=512)),
                (
                    "principal_id",
                    models.PositiveBigIntegerField(
                        blank=True, db_index=True, null=True
                    ),
                ),
                (
                    "identity_link_id",
                    models.PositiveBigIntegerField(blank=True, null=True),
                ),
                ("actor_id", models.UUIDField(blank=True, null=True)),
                ("group_id", models.UUIDField(blank=True, null=True)),
                (
                    "correlation_id",
                    models.CharField(db_index=True, max_length=64),
                ),
                ("details", models.JSONField(blank=True, default=dict)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "operator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-timestamp",),
            },
        ),
        migrations.CreateModel(
            name="PurgeGrant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "granted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "grantee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="purge_grants",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="purge_grants",
                        to="catalog.catalogentity",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Relation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("predicate", models.CharField(max_length=32)),
                (
                    "object_entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="relations_as_object",
                        to="catalog.catalogentity",
                    ),
                ),
                (
                    "subject_entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="relations_as_subject",
                        to="catalog.catalogentity",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ActorDetails",
            fields=[
                (
                    "entity",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="actor_details",
                        serialize=False,
                        to="catalog.catalogentity",
                    ),
                ),
                ("display_name", models.CharField(blank=True, max_length=255)),
                ("email", models.EmailField(blank=True, max_length=254)),
                (
                    "account",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="catalog_actor",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ApiDetails",
            fields=[
                (
                    "entity",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="api_details",
                        serialize=False,
                        to="catalog.catalogentity",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("openapi", "OpenAPI"),
                            ("grpc", "gRPC"),
                            ("asyncapi", "AsyncAPI"),
                            ("graphql", "GraphQL"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "spec_source",
                    models.CharField(
                        choices=[
                            ("none", "None"),
                            ("inline", "Inline"),
                            ("url", "URL"),
                        ],
                        default="none",
                        max_length=16,
                    ),
                ),
                ("spec_url", models.URLField(blank=True)),
                (
                    "spec_content",
                    models.TextField(
                        blank=True,
                        help_text="Resolved spec snapshot, regardless of source",  # noqa: E501
                    ),
                ),
                (
                    "spec_resolved_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("spec_resolve_failed", models.BooleanField(default=False)),
                (
                    "endpoints_synced_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("endpoints_sync_failed", models.BooleanField(default=False)),
                (
                    "operations_synced_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("operations_sync_failed", models.BooleanField(default=False)),
                (
                    "resolved_base_url",
                    models.CharField(blank=True, max_length=2048),
                ),
                (
                    "resolved_protocol",
                    models.CharField(blank=True, max_length=32),
                ),
                (
                    "system",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="apis",
                        to="catalog.catalogentity",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ComponentDetails",
            fields=[
                (
                    "entity",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="component_details",
                        serialize=False,
                        to="catalog.catalogentity",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("service", "Service"),
                            ("website", "Website"),
                            ("library", "Library"),
                            ("worker", "Worker"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "lifecycle",
                    models.CharField(
                        choices=[
                            ("experimental", "Experimental"),
                            ("production", "Production"),
                            ("deprecated", "Deprecated"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "consumes_apis",
                    models.ManyToManyField(
                        blank=True,
                        related_name="consumed_by",
                        to="catalog.catalogentity",
                    ),
                ),
                (
                    "depends_on",
                    models.ManyToManyField(
                        blank=True,
                        related_name="depended_on_by",
                        to="catalog.catalogentity",
                    ),
                ),
                (
                    "provides_apis",
                    models.ManyToManyField(
                        blank=True,
                        related_name="provided_by",
                        to="catalog.catalogentity",
                    ),
                ),
                (
                    "system",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="components",
                        to="catalog.catalogentity",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LegacyGroupMembershipPair",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "catalogentity",
                    models.ForeignKey(
                        db_column="catalogentity_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="catalog.catalogentity",
                    ),
                ),
                (
                    "groupdetails",
                    models.ForeignKey(
                        db_column="groupdetails_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="catalog.groupdetails",
                    ),
                ),
            ],
            options={
                "db_table": "catalog_groupdetails_members",
            },
        ),
        migrations.CreateModel(
            name="GroupMembershipGrant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source_kind",
                    models.CharField(
                        choices=[
                            ("manual", "Manual"),
                            ("provider", "Authentication provider"),
                        ],
                        default="manual",
                        max_length=16,
                    ),
                ),
                (
                    "external_key",
                    models.CharField(blank=True, default="", max_length=512),
                ),
                ("legacy_unclassified", models.BooleanField(default=False)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "last_confirmed_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "actor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="membership_grants",
                        to="catalog.catalogentity",
                    ),
                ),
                (
                    "identity_link",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="membership_grants",
                        to="catalog.externalidentitylink",
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="membership_grants",
                        to="catalog.groupdetails",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="groupdetails",
            name="members",
            field=models.ManyToManyField(
                blank=True,
                related_name="member_of",
                through="catalog.GroupMembershipGrant",
                through_fields=("group", "actor"),
                to="catalog.catalogentity",
            ),
        ),
        migrations.CreateModel(
            name="ResourceDetails",
            fields=[
                (
                    "entity",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="resource_details",
                        serialize=False,
                        to="catalog.catalogentity",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("database", "Database"),
                            ("cache", "Cache"),
                            ("bucket", "Bucket"),
                            ("queue", "Queue"),
                            ("cluster", "Cluster"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "system",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="resources",
                        to="catalog.catalogentity",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="catalogentity",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("name"),
                models.F("namespace"),
                models.F("kind"),
                name="catalog_entity_unique_kind_namespace_name",
            ),
        ),
        migrations.AddIndex(
            model_name="architecturerelationship",
            index=models.Index(
                fields=["source"], name="catalog_arc_source__fa4746_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="architecturerelationship",
            index=models.Index(
                fields=["target"], name="catalog_arc_target__1fa295_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="architecturerelationship",
            constraint=models.CheckConstraint(
                condition=models.Q(("label", ""), _negated=True),
                name="catalog_architecture_relationship_label_nonempty",
            ),
        ),
        migrations.AddConstraint(
            model_name="externalidentitylink",
            constraint=models.UniqueConstraint(
                fields=("provider_id", "source_id", "external_subject"),
                name="catalog_unique_external_identity_source",
            ),
        ),
        migrations.AddConstraint(
            model_name="flow",
            constraint=models.UniqueConstraint(
                fields=("system", "name"),
                name="catalog_flow_unique_system_name",
            ),
        ),
        migrations.AddConstraint(
            model_name="purgegrant",
            constraint=models.UniqueConstraint(
                fields=("group", "grantee"),
                name="purge_grant_unique_group_grantee",
            ),
        ),
        migrations.AddIndex(
            model_name="relation",
            index=models.Index(
                fields=["subject_entity", "predicate"],
                name="catalog_rel_subject_a9b50a_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="relation",
            index=models.Index(
                fields=["object_entity", "predicate"],
                name="catalog_rel_object__aeab79_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="relation",
            constraint=models.UniqueConstraint(
                fields=("subject_entity", "predicate", "object_entity"),
                name="catalog_relation_unique_edge",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="legacygroupmembershippair",
            unique_together={("groupdetails", "catalogentity")},
        ),
        migrations.AddIndex(
            model_name="groupmembershipgrant",
            index=models.Index(
                fields=["actor", "group"], name="catalog_grant_actor_group"
            ),
        ),
        migrations.AddIndex(
            model_name="groupmembershipgrant",
            index=models.Index(
                fields=["group", "actor", "expires_at"],
                name="catalog_grant_group_expiry",
            ),
        ),
        migrations.AddIndex(
            model_name="groupmembershipgrant",
            index=models.Index(
                fields=["identity_link", "external_key"],
                name="catalog_grant_link_key",
            ),
        ),
        migrations.AddConstraint(
            model_name="groupmembershipgrant",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("expires_at__isnull", True),
                        ("external_key", ""),
                        ("identity_link__isnull", True),
                        ("source_kind", "manual"),
                    ),
                    models.Q(
                        ("identity_link__isnull", False),
                        ("legacy_unclassified", False),
                        ("source_kind", "provider"),
                    ),
                    _connector="OR",
                ),
                name="catalog_membership_grant_source_shape",
            ),
        ),
        migrations.AddConstraint(
            model_name="groupmembershipgrant",
            constraint=models.UniqueConstraint(
                condition=models.Q(("source_kind", "manual")),
                fields=("group", "actor"),
                name="catalog_unique_manual_membership_grant",
            ),
        ),
        migrations.AddConstraint(
            model_name="groupmembershipgrant",
            constraint=models.UniqueConstraint(
                condition=models.Q(("source_kind", "provider")),
                fields=("group", "actor", "identity_link", "external_key"),
                name="catalog_unique_provider_membership_grant",
            ),
        ),
    ]
