# Generated by Django 5.2.17 on 2026-08-24 08:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0002_user_account"),
    ]

    operations = [
        migrations.CreateModel(
            name="Relation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "subject_kind",
                    models.CharField(
                        choices=[
                            ("system", "System"),
                            ("component", "Component"),
                            ("resource", "Resource"),
                            ("api", "API"),
                            ("group", "Group"),
                            ("user", "User"),
                        ],
                        max_length=16,
                    ),
                ),
                ("subject_id", models.BigIntegerField()),
                ("predicate", models.CharField(max_length=32)),
                (
                    "object_kind",
                    models.CharField(
                        choices=[
                            ("system", "System"),
                            ("component", "Component"),
                            ("resource", "Resource"),
                            ("api", "API"),
                            ("group", "Group"),
                            ("user", "User"),
                        ],
                        max_length=16,
                    ),
                ),
                ("object_id", models.BigIntegerField()),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["subject_kind", "subject_id"],
                        name="catalog_rel_subject_13e139_idx",
                    ),
                    models.Index(
                        fields=["object_kind", "object_id"],
                        name="catalog_rel_object__30773b_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=(
                            "subject_kind",
                            "subject_id",
                            "predicate",
                            "object_kind",
                            "object_id",
                        ),
                        name="catalog_relation_unique_edge",
                    )
                ],
            },
        ),
    ]
