# Generated by Django 5.2.17 on 2026-08-24 13:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0003_relations"),
    ]

    operations = [
        migrations.AddField(
            model_name="api",
            name="source_kind",
            field=models.CharField(
                choices=[("manual", "Manual"), ("yaml", "YAML")],
                default="manual",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="component",
            name="source_kind",
            field=models.CharField(
                choices=[("manual", "Manual"), ("yaml", "YAML")],
                default="manual",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="resource",
            name="source_kind",
            field=models.CharField(
                choices=[("manual", "Manual"), ("yaml", "YAML")],
                default="manual",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="system",
            name="source_kind",
            field=models.CharField(
                choices=[("manual", "Manual"), ("yaml", "YAML")],
                default="manual",
                max_length=16,
            ),
        ),
    ]
