# Generated by Django 5.2.17 on 2026-08-24 18:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0005_tag"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tag",
            name="color",
            field=models.CharField(
                choices=[
                    ("gray", "gray"),
                    ("red", "red"),
                    ("orange", "orange"),
                    ("yellow", "yellow"),
                    ("green", "green"),
                    ("blue", "blue"),
                    ("purple", "purple"),
                    ("pink", "pink"),
                ],
                default="gray",
                max_length=32,
            ),
        ),
    ]
