# Generated by Django 6.1 on 2026-08-27 15:24

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0010_add_documentation"),
    ]

    operations = [
        migrations.CreateModel(
            name="ArchitectureRelationship",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source_kind",
                    models.CharField(
                        choices=[
                            ("system", "System"),
                            ("component", "Component"),
                            ("resource", "Resource"),
                            ("api", "API"),
                            ("group", "Group"),
                            ("user", "User"),
                        ],
                        max_length=16,
                    ),
                ),
                ("source_id", models.BigIntegerField()),
                (
                    "target_kind",
                    models.CharField(
                        choices=[
                            ("system", "System"),
                            ("component", "Component"),
                            ("resource", "Resource"),
                            ("api", "API"),
                            ("group", "Group"),
                            ("user", "User"),
                        ],
                        max_length=16,
                    ),
                ),
                ("target_id", models.BigIntegerField()),
                ("label", models.CharField(max_length=255)),
                ("technology", models.CharField(blank=True, max_length=255)),
                (
                    "interaction_kind",
                    models.CharField(
                        choices=[
                            ("synchronous", "Synchronous"),
                            ("asynchronous", "Asynchronous"),
                            ("data-access", "Data access"),
                            ("manual", "Manual"),
                        ],
                        default="manual",
                        max_length=16,
                    ),
                ),
                (
                    "tags",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=100),
                        blank=True,
                        default=list,
                    ),
                ),
                (
                    "origin",
                    models.CharField(
                        choices=[("manual", "Manual"), ("yaml", "YAML")],
                        default="manual",
                        max_length=16,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["source_kind", "source_id"],
                        name="catalog_arc_source__7ae3e1_idx",
                    ),
                    models.Index(
                        fields=["target_kind", "target_id"],
                        name="catalog_arc_target__a5c1cf_idx",
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("label", ""), _negated=True),
                        name="catalog_architecture_relationship_label_nonempty",
                    )
                ],
            },
        ),
    ]
