# Generated by Django 6.1 on 2026-09-04 16:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0014_external_identity_link"),
    ]

    operations = [
        migrations.AddField(
            model_name="apidetails",
            name="endpoints_sync_failed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="apidetails",
            name="endpoints_synced_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
