# Generated by Django 6.1 on 2026-09-07 11:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0015_apidetails_endpoints_sync_failed_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="apidetails",
            name="operations_sync_failed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="apidetails",
            name="operations_synced_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
