# Generated by Django 6.1 on 2026-09-10 05:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0016_apidetails_operations_sync"),
    ]

    operations = [
        migrations.AddField(
            model_name="catalogentity",
            name="status",
            field=models.CharField(
                choices=[("active", "Active"), ("removed", "Removed")],
                default="active",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="entityauditrecord",
            name="action",
            field=models.CharField(
                choices=[
                    ("create", "Create"),
                    ("update", "Update"),
                    ("delete", "Delete"),
                    ("remove", "Remove"),
                    ("revive", "Revive"),
                ],
                max_length=16,
            ),
        ),
    ]
