# Generated by Django 6.1 on 2026-09-10 06:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0018_alter_catalogentity_owner_purgegrant"),
    ]

    operations = [
        migrations.AlterField(
            model_name="entityauditrecord",
            name="action",
            field=models.CharField(
                choices=[
                    ("create", "Create"),
                    ("update", "Update"),
                    ("delete", "Delete"),
                    ("remove", "Remove"),
                    ("revive", "Revive"),
                    ("purge", "Purge"),
                ],
                max_length=16,
            ),
        ),
    ]
