# Generated by Django 6.1 on 2026-09-11 16:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0019_alter_entityauditrecord_action"),
    ]

    operations = [
        migrations.AddField(
            model_name="flow",
            name="autolayout_enabled",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="flow",
            name="layout_direction",
            field=models.CharField(
                choices=[
                    ("LAYOUT_LEFT_RIGHT", "Left-right"),
                    ("LAYOUT_TOP_DOWN", "Top-down"),
                ],
                default="LAYOUT_LEFT_RIGHT",
                max_length=32,
            ),
        ),
    ]
