# Generated by Django 6.1 on 2026-09-13 08:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0020_flow_autolayout_enabled_flow_layout_direction"),
    ]

    operations = [
        migrations.AddField(
            model_name="flow",
            name="layout_engine",
            field=models.CharField(
                choices=[("dagre", "Dagre"), ("elk", "ELK.js")],
                default="dagre",
                max_length=32,
            ),
        ),
    ]
