# Generated by Django 6.1 on 2026-09-16 14:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0021_flow_layout_engine"),
    ]

    operations = [
        migrations.CreateModel(
            name="CatalogHomeSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("about_markdown", models.TextField(blank=True)),
            ],
        ),
    ]
