# Generated by Django 6.1 on 2026-09-17 20:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0023_seed_catalog_home_settings"),
    ]

    operations = [
        migrations.AddField(
            model_name="apidetails",
            name="resolved_base_url",
            field=models.CharField(blank=True, max_length=2048),
        ),
        migrations.AddField(
            model_name="apidetails",
            name="resolved_protocol",
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
