"""Lock -> `INSTALLED_APPS` / frontend composition module generation

Turns a resolved `Lock` into the two artifacts Core's static startup phase
and frontend composition step read: the backend's `SELECTED_PLUGINS`
tuple (`server/settings/selected_plugins.py`) and the frontend's
`installedFrontendPlugins` composition module
(`core/frontend/src/plugins/composition.ts`) — replacing what a developer
used to hand-edit in both places (a later change can
replace its contents wholesale with composer-generated output).

Both target files stay fixed, well-known repo paths, not composer-chosen
locations — other code imports them by that exact path
(`server/settings/components/common.py` imports `SELECTED_PLUGINS`;
`composition.test.ts` and plugin detail pages import
`installedFrontendPlugins`/`composedContributions` from `composition.ts`;
`importBoundary.test.ts` asserts `composition.ts` is the *only* place a
plugin package is imported into core). Generation therefore replaces
those files' contents wholesale rather than writing to a separate
generated module the hand-written file would import.
"""

import json
from pathlib import Path
from pprint import pformat

import yaml

from .lock import Lock, LockedService
from .services import wire_plugin_config

CORE_BACKEND_MODULE = "server.apps.catalog.plugin"
"""Authentication/Catalog Core isn't itself an operator-selectable plugin
(it's not in any manifest), but `SELECTED_PLUGINS` has always listed it
first — generation preserves that."""

CORE_FRONTEND_EXPORT = "corePlugin"
CORE_FRONTEND_IMPORT_PATH = "./core"

_GENERATED_HEADER = (
    "GENERATED by `atlas-compose generate` from {distribution}'s lock "
    "file. Do not edit by hand — regenerate from the manifest/lock "
    "instead."
)


def backend_module_path(package: str) -> str:
    """`atlas-plugin-apis` -> `atlas_plugin_apis.plugin`, matching every
    existing plugin package's `pyproject.toml` `packages` entry (the
    PyPI-style dashed name importable as its underscored top-level
    package) plus the `<package>.plugin` module convention
    `SELECTED_PLUGINS` has always pointed descriptors at."""
    return f"{package.replace('-', '_')}.plugin"


def frontend_export_name(plugin_id: str) -> str:
    """`atlas.database-schema` -> `databaseSchemaPlugin`, matching every
    existing frontend plugin package's own
    `export const <name>Plugin = defineFrontendPlugin({{id: '<plugin_id>',
    ...}})` convention."""
    suffix = plugin_id.rsplit(".", 1)[-1]
    first, *rest = suffix.split("-")
    camel_case = first + "".join(word.capitalize() for word in rest)
    return f"{camel_case}Plugin"


def generate_selected_plugins(
    lock: Lock,
    *,
    core_module: str = CORE_BACKEND_MODULE,
) -> tuple[str, ...]:
    """The `SELECTED_PLUGINS` tuple `lock` implies: `core_module` first,
    then each locked plugin with a backend artifact, in the lock's own
    (manifest-declared) order.

    Includes a `disabled` plugin's module — its Django app still needs to
    install so its migrations still apply; only
    `DISABLED_PLUGINS`, not this tuple, is where disabled-ness is
    represented.
    """
    modules = [core_module]
    for locked in lock.plugins.values():
        if locked.backend is not None:
            modules.append(backend_module_path(locked.backend.package))
    return tuple(modules)


def generate_disabled_plugin_ids(lock: Lock) -> frozenset[str]:
    """Plugin ids (not `{id}@{version}` keys) locked with `disabled: true`
    what the runtime entry-point-loading phase
    checks to skip a disabled plugin's contribution/registration loading."""
    return frozenset(
        key.rsplit("@", 1)[0] for key, locked in lock.plugins.items() if locked.disabled
    )


def generate_plugin_configs(lock: Lock) -> dict[str, dict[str, object]]:
    """Return unresolved, namespaced runtime config keyed by plugin id."""

    configs = {}
    for key, locked in lock.plugins.items():
        plugin_id = key.rsplit("@", 1)[0]
        if locked.disabled:
            continue
        config = wire_plugin_config(plugin_id, locked.config, lock.services)
        if config:
            configs[plugin_id] = config
    return configs


COMPOSE_APPLICATION_SERVICES = ("initializer", "backend", "ingestor")
"""Base `docker-compose.yml` services that load plugin settings, and so need
the wired secrets, and that reach the plugins' services. The initializer
loads settings to migrate, and fails at startup without the key."""

COMPOSE_SERVICES_NETWORK = "database"
"""Internal network `backend` and `ingestor` already share with Postgres."""


def _volume_name(service: LockedService) -> str:
    return f"{service.id}-data"


def generate_compose_services(lock: Lock) -> dict[str, object]:
    """A compose override running every generated (non-external) required
    service next to the base stack, plus the secret each plugin's wiring
    references. Empty when no selected plugin needs a service."""
    if not lock.services:
        return {}
    services: dict[str, object] = {}
    volumes: dict[str, object] = {}
    app_environment: dict[str, str] = {}
    app_depends_on: dict[str, object] = {}
    for locked in lock.services.values():
        if locked.secret_from_env is not None:
            app_environment[locked.secret_from_env] = (
                f"${{{locked.secret_from_env}:?Set {locked.secret_from_env} "
                f"(access key for {locked.id})}}"
            )
        if locked.external or locked.id in services:
            continue
        definition: dict[str, object] = {
            "image": locked.image,
            "healthcheck": {
                "test": ["CMD", *locked.health_check],
                "interval": "5s",
                "timeout": "5s",
                "retries": 12,
            },
            "networks": [COMPOSE_SERVICES_NETWORK],
        }
        if locked.secret_env is not None and locked.secret_from_env is not None:
            definition["environment"] = {
                locked.secret_env: f"${{{locked.secret_from_env}}}"
            }
        if locked.data_path is not None:
            definition["volumes"] = [f"{_volume_name(locked)}:{locked.data_path}"]
            volumes[_volume_name(locked)] = {}
        services[locked.id] = definition
        app_depends_on[locked.id] = {"condition": "service_healthy"}
    for name in COMPOSE_APPLICATION_SERVICES:
        application: dict[str, object] = {}
        if app_environment:
            application["environment"] = dict(app_environment)
        if app_depends_on:
            application["depends_on"] = {
                key: dict(value) for key, value in app_depends_on.items()
            }
        if application:
            services[name] = application
    document: dict[str, object] = {"services": services}
    if volumes:
        document["volumes"] = volumes
    return document


def render_compose_services(lock: Lock) -> str:
    header = _GENERATED_HEADER.format(distribution=lock.distribution)
    document = generate_compose_services(lock) or {"services": {}}
    return f"# {header}\n" + yaml.safe_dump(document, sort_keys=False)


def dump_compose_services(lock: Lock, path: Path) -> None:
    path.write_text(render_compose_services(lock))


def render_selected_plugins_module(
    lock: Lock,
    *,
    core_module: str = CORE_BACKEND_MODULE,
) -> str:
    """Render `server/settings/selected_plugins.py`'s replacement content."""
    modules = generate_selected_plugins(lock, core_module=core_module)
    disabled_ids = generate_disabled_plugin_ids(lock)
    plugin_configs = generate_plugin_configs(lock)
    header = _GENERATED_HEADER.format(distribution=lock.distribution)
    entries = "".join(f"    {module!r},\n" for module in modules)
    disabled_entries = "".join(
        f"    {plugin_id!r},\n" for plugin_id in sorted(disabled_ids)
    )
    auth_config = lock.auth.model_dump(by_alias=True)
    return (
        f'"""{header}"""\n\n'
        "SELECTED_PLUGINS = (\n"
        f"{entries}"
        ")\n\n"
        "DISABLED_PLUGINS = frozenset({\n"
        f"{disabled_entries}"
        "})\n\n"
        f"PLUGIN_CONFIGS = {pformat(plugin_configs, sort_dicts=False)}\n\n"
        f"AUTHENTICATION = {pformat(auth_config, sort_dicts=False)}\n"
    )


def dump_selected_plugins_module(
    lock: Lock,
    path: Path,
    *,
    core_module: str = CORE_BACKEND_MODULE,
) -> None:
    path.write_text(
        render_selected_plugins_module(lock, core_module=core_module),
    )


def generate_frontend_plugins(
    lock: Lock,
) -> tuple[tuple[str, str], ...]:
    """`(export_name, npm_package)` pairs for every locked plugin with a
    frontend artifact, in the lock's own (manifest-declared) order.

    A `disabled` plugin is omitted entirely: unlike the backend (where the
    Django app still installs so migrations apply), the frontend has no
    separate runtime "load" step to skip disabled contributions at
    suppressing them is this generation-time
    exclusion."""
    entries = []
    for key, locked in lock.plugins.items():
        if locked.frontend is not None and not locked.disabled:
            plugin_id = key.rsplit("@", 1)[0]
            entries.append(
                (
                    frontend_export_name(plugin_id),
                    locked.frontend.package,
                )
            )
    return tuple(entries)


def render_composition_module(
    lock: Lock,
    *,
    core_export: str = CORE_FRONTEND_EXPORT,
    core_import_path: str = CORE_FRONTEND_IMPORT_PATH,
) -> str:
    """Render `core/frontend/src/plugins/composition.ts`'s replacement
    content, preserving its existing exports
    (`installedFrontendPlugins`, `composedContributions`) so nothing
    importing this module needs to change."""
    entries = generate_frontend_plugins(lock)
    auth_bootstrap = generate_frontend_auth_bootstrap(lock)
    auth_json = json.dumps(auth_bootstrap, indent=2, separators=(",", ": "))
    header = _GENERATED_HEADER.format(distribution=lock.distribution)
    import_lines = "".join(
        f"import {{ {name} }} from '{package}'\n" for name, package in entries
    )
    array_lines = "".join(f"  {name},\n" for name, _ in entries)
    return (
        f"// {header}\n"
        f"{import_lines}"
        "import { composeFrontendPlugins } from '@atlas/plugin-api'\n"
        f"import {{ {core_export} }} from '{core_import_path}'\n"
        "\n"
        "export const installedFrontendPlugins = [\n"
        f"{array_lines}"
        f"  {core_export},\n"
        "] as const\n"
        "\n"
        "export const composedContributions = "
        "composeFrontendPlugins(installedFrontendPlugins)\n"
        "\n"
        "export const authenticationBootstrap = "
        f"{auth_json} as const\n"
    )


def generate_backend_auth_config(lock: Lock) -> dict[str, object]:
    """Complete, non-secret Core policy generated from the resolved lock."""

    return lock.auth.model_dump(by_alias=True)


def generate_frontend_auth_bootstrap(lock: Lock) -> dict[str, object]:
    """Presentation-only auth selection safe to include in a browser bundle."""

    providers = []
    for provider in lock.auth.providers:
        item: dict[str, object] = {
            "id": provider.id,
            "contractVersion": provider.contract_version,
            "flowKind": provider.flow_kind,
            "presentation": provider.presentation.model_dump(
                by_alias=True,
                exclude_none=True,
            ),
            "remoteLogout": provider.remote_logout,
            "isDefault": provider.id == lock.auth.default,
        }
        if provider.id == "atlas.auth.local":
            item["signupOpen"] = provider.signup == "enabled"
        providers.append(item)
    return {
        "providers": providers,
        "defaultProviderId": lock.auth.default,
        "providerChoiceUrl": "/login?choose-provider=1",
    }


def dump_composition_module(
    lock: Lock,
    path: Path,
    *,
    core_export: str = CORE_FRONTEND_EXPORT,
    core_import_path: str = CORE_FRONTEND_IMPORT_PATH,
) -> None:
    path.write_text(
        render_composition_module(
            lock,
            core_export=core_export,
            core_import_path=core_import_path,
        )
    )
