#!/usr/bin/env python3
"""Regenerates two vendored, checked-in copies of `@gravity-ui/icons`' own
`metadata.json` — the same file `plugins/flows/frontend/src/lib/
gravityIcons.ts` reads client-side to validate a Flow step's `icon` field
and power its icon picker:

- `mcp/atlas_mcp/_gravity_icons.py`: name + searchable keyword/category
  blob, for the `search_flow_icons` MCP tool (`mcp/atlas_mcp/icons.py`) to
  match a free-text query against.
- `plugins/flows/backend/atlas_plugin_flows/_gravity_icons.py`: a flat name
  set, for `atlas_plugin_flows.api.step_schemas.StepIn` to validate a
  submitted `icon` value against at write time.

Both processes are pure Python with no JS runtime and no npm dependency of
their own (`mcp/atlas_mcp/server.py`'s own docstring: "this process holds no
Django import ... extends to not holding a node_modules dependency"; the
same is true in reverse for the Django backend never importing from
`node_modules`). Rather than shelling out to Node at import time, or
fetching the npm package over the network at startup, this script is a
one-off, manually-run sync: it reads the copy of `@gravity-ui/icons`
already installed at the repo root (a peer dependency of
`plugins/flows/frontend`) and writes two small, static Python modules — no
different in spirit from committing a lockfile.

Run this after bumping `@gravity-ui/icons` in `plugins/flows/frontend`'s
`package.json` (from the repo root, with `node_modules` installed):

    python scripts/sync_gravity_icons.py

It only ever touches the two generated files above — verify the diff (an
icon rename/removal is possible, if rare) before committing.
"""

import json
from pathlib import Path

_REPO_ROOT = Path(__file__).resolve().parent.parent
_SOURCE = _REPO_ROOT / "node_modules" / "@gravity-ui" / "icons" / "metadata.json"
_MCP_OUTPUT = _REPO_ROOT / "mcp" / "atlas_mcp" / "_gravity_icons.py"
_FLOWS_OUTPUT = (
    _REPO_ROOT
    / "plugins"
    / "flows"
    / "backend"
    / "atlas_plugin_flows"
    / "_gravity_icons.py"
)

_MCP_HEADER = '''"""Generated by `scripts/sync_gravity_icons.py` from
`@gravity-ui/icons`'s own `metadata.json` (version {version}) — do not edit
by hand; see that script's docstring to regenerate.

`GRAVITY_ICONS` pairs every icon's component name (the exact string a Flow
step's `icon` field expects — see `plugins/flows/frontend/src/lib/
gravityIcons.ts`) with a lowercase search blob of its own keywords and
categories, for `icons.search_flow_icons` to match a free-text query
against.
"""

GRAVITY_ICONS: tuple[tuple[str, str], ...] = (
'''

_FLOWS_HEADER = '''"""Generated by `scripts/sync_gravity_icons.py` from
`@gravity-ui/icons`'s own `metadata.json` (version {version}) — do not edit
by hand; see that script's docstring to regenerate.

`GRAVITY_ICON_NAMES` is every valid `@gravity-ui/icons` component name — the
same set `plugins/flows/frontend/src/lib/gravityIcons.ts` validates a Flow
step's `icon` field against client-side. `atlas_plugin_flows.api.
step_schemas.StepIn` validates against this same set server-side, so a
client that bypasses the web UI (e.g. an MCP tool call) can't silently
store an unrenderable icon name.
"""

GRAVITY_ICON_NAMES: frozenset[str] = frozenset(
    (
'''

_FLOWS_FOOTER = """    )
)
"""


def _search_blob(icon: dict) -> str:
    words = [icon["name"], *icon["keywords"], *icon["categories"]]
    return " ".join(dict.fromkeys(word.lower() for word in words if word))


def _write_mcp_output(icons: list[dict], version: str) -> None:
    lines = [_MCP_HEADER.format(version=version)]
    for icon in icons:
        lines.append(f"    ({icon['componentName']!r}, {_search_blob(icon)!r}),\n")
    lines.append(")\n")
    _MCP_OUTPUT.write_text("".join(lines), encoding="utf-8")


def _write_flows_output(icons: list[dict], version: str) -> None:
    lines = [_FLOWS_HEADER.format(version=version)]
    for icon in icons:
        lines.append(f"        {icon['componentName']!r},\n")
    lines.append(_FLOWS_FOOTER)
    _FLOWS_OUTPUT.write_text("".join(lines), encoding="utf-8")


def main() -> None:
    package_json = json.loads(
        (_SOURCE.parent / "package.json").read_text(encoding="utf-8")
    )
    version = package_json["version"]
    icons = json.loads(_SOURCE.read_text(encoding="utf-8"))["icons"]

    _write_mcp_output(icons, version)
    _write_flows_output(icons, version)

    print(f"Wrote {len(icons)} icons to {_MCP_OUTPUT}")
    print(f"Wrote {len(icons)} icons to {_FLOWS_OUTPUT}")


if __name__ == "__main__":
    main()
