"""Lock -> `INSTALLED_APPS` / frontend composition module generation tests
(`deployment-manifest-and-lock` spec)."""

from atlas_composer.generate import (
    backend_module_path,
    dump_composition_module,
    dump_selected_plugins_module,
    frontend_export_name,
    generate_backend_auth_config,
    generate_disabled_plugin_ids,
    generate_frontend_auth_bootstrap,
    generate_frontend_plugins,
    generate_plugin_configs,
    generate_selected_plugins,
    render_composition_module,
    render_selected_plugins_module,
)
from atlas_composer.lock import (
    Lock,
    LockedBackendArtifact,
    LockedFrontendArtifact,
    LockedPlugin,
)

REAL_DISTRIBUTION_ORDER = (
    (
        'atlas.standard-catalog',
        'atlas-plugin-standard-catalog',
        '@atlas/plugin-standard-catalog',
    ),
    ('atlas.apis', 'atlas-plugin-apis', '@atlas/plugin-apis'),
    ('atlas.c4', 'atlas-plugin-c4', '@atlas/plugin-c4'),
    (
        'atlas.database-schema',
        'atlas-plugin-database-schema',
        '@atlas/plugin-database-schema',
    ),
    ('atlas.ingestion', 'atlas-plugin-ingestion', None),
)
"""Matches `server/settings/selected_plugins.py`'s real `SELECTED_PLUGINS`
order and `core/frontend/src/plugins/composition.ts`'s real
`installedFrontendPlugins` order (minus `atlas.ingestion`, which has no
frontend artifact) — a parity fixture, not a real resolved lock."""


def _lock(entries=REAL_DISTRIBUTION_ORDER, *, disabled_ids=frozenset()) -> Lock:
    plugins = {}
    for plugin_id, backend_package, frontend_package in entries:
        frontend = None
        if frontend_package is not None:
            frontend = LockedFrontendArtifact(
                package=frontend_package, version='0.1.0', integrity='sha512-x',
            )
        plugins[f'{plugin_id}@0.1.0'] = LockedPlugin(
            backend=LockedBackendArtifact(
                package=backend_package, version='0.1.0', hash='sha256:x',
            ),
            frontend=frontend,
            disabled=plugin_id in disabled_ids,
        )
    return Lock(
        distribution='company.atlas@2026.08', core='0.1.0', plugins=plugins,
    )


def test_backend_module_path_matches_pyproject_packages_convention():
    assert backend_module_path('atlas-plugin-apis') == (
        'atlas_plugin_apis.plugin'
    )
    assert backend_module_path(
        'atlas-plugin-database-schema',
    ) == 'atlas_plugin_database_schema.plugin'


def test_frontend_export_name_matches_each_package_own_convention():
    assert frontend_export_name('atlas.apis') == 'apisPlugin'
    assert frontend_export_name('atlas.c4') == 'c4Plugin'
    assert frontend_export_name(
        'atlas.database-schema',
    ) == 'databaseSchemaPlugin'
    assert frontend_export_name(
        'atlas.standard-catalog',
    ) == 'standardCatalogPlugin'


def test_generate_selected_plugins_reproduces_the_real_selection():
    modules = generate_selected_plugins(_lock())

    assert modules == (
        'server.apps.catalog.plugin',
        'atlas_plugin_standard_catalog.plugin',
        'atlas_plugin_apis.plugin',
        'atlas_plugin_c4.plugin',
        'atlas_plugin_database_schema.plugin',
        'atlas_plugin_ingestion.plugin',
    )


def test_render_selected_plugins_module_is_valid_python_defining_the_tuple():
    source = render_selected_plugins_module(_lock())

    namespace: dict[str, object] = {}
    exec(source, namespace)  # noqa: S102 - trusted generated source under test

    assert namespace['SELECTED_PLUGINS'] == generate_selected_plugins(_lock())
    assert namespace['DISABLED_PLUGINS'] == frozenset()
    assert namespace['PLUGIN_CONFIGS'] == {}
    assert 'GENERATED by' in source


def test_generate_plugin_configs_preserves_unresolved_namespaced_values():
    lock = _lock()
    plugin_key = 'atlas.standard-catalog@0.1.0'
    configured = lock.model_copy(update={
        'plugins': {
            **lock.plugins,
            plugin_key: lock.plugins[plugin_key].model_copy(update={
                'config': {
                    'fixturePassword': {'fromEnv': 'ATLAS_FIXTURE_PASSWORD'},
                    'developmentEnabled': True,
                },
            }),
        },
    })

    assert generate_plugin_configs(configured) == {
        'atlas.standard-catalog': {
            'fixturePassword': {'fromEnv': 'ATLAS_FIXTURE_PASSWORD'},
            'developmentEnabled': True,
        },
    }
    assert 'resolved-password' not in render_selected_plugins_module(configured)


def test_generate_selected_plugins_includes_a_disabled_plugin_s_module():
    # A disabled plugin's Django app still installs (plugin-lifecycle spec:
    # disabling keeps code, only suppresses contributions), so it must stay
    # in SELECTED_PLUGINS.
    modules = generate_selected_plugins(_lock(disabled_ids={'atlas.apis'}))

    assert 'atlas_plugin_apis.plugin' in modules


def test_generate_selected_plugins_includes_ingestion_when_manifest_omits_it():
    # Core's own `CatalogEntity.ingested_from` FK hard-depends on
    # `atlas.ingestion`'s model (generate.py's `CORE_REQUIRED_PLUGIN_ID`), so
    # a manifest that omits it entirely must not make it absent from
    # `SELECTED_PLUGINS` — Django would fail its own field/app checks.
    entries = tuple(e for e in REAL_DISTRIBUTION_ORDER if e[0] != 'atlas.ingestion')
    modules = generate_selected_plugins(_lock(entries))

    assert 'atlas_plugin_ingestion.plugin' in modules


def test_generate_disabled_plugin_ids_includes_ingestion_when_manifest_omits_it():
    entries = tuple(e for e in REAL_DISTRIBUTION_ORDER if e[0] != 'atlas.ingestion')

    assert generate_disabled_plugin_ids(_lock(entries)) == frozenset({'atlas.ingestion'})


def test_generate_disabled_plugin_ids_returns_bare_ids_not_lock_keys():
    disabled = generate_disabled_plugin_ids(
        _lock(disabled_ids={'atlas.apis', 'atlas.c4'}),
    )

    assert disabled == frozenset({'atlas.apis', 'atlas.c4'})


def test_generate_disabled_plugin_ids_empty_when_nothing_disabled():
    assert generate_disabled_plugin_ids(_lock()) == frozenset()


def test_render_selected_plugins_module_lists_disabled_plugin_ids():
    source = render_selected_plugins_module(
        _lock(disabled_ids={'atlas.apis'}),
    )

    namespace: dict[str, object] = {}
    exec(source, namespace)  # noqa: S102 - trusted generated source under test

    assert namespace['DISABLED_PLUGINS'] == frozenset({'atlas.apis'})


def test_generate_frontend_plugins_reproduces_the_real_selection():
    entries = generate_frontend_plugins(_lock())

    assert entries == (
        ('standardCatalogPlugin', '@atlas/plugin-standard-catalog'),
        ('apisPlugin', '@atlas/plugin-apis'),
        ('c4Plugin', '@atlas/plugin-c4'),
        ('databaseSchemaPlugin', '@atlas/plugin-database-schema'),
    )
    # atlas.ingestion has no frontend artifact and is correctly omitted.
    ingestion_present = any(
        package == 'atlas-plugin-ingestion' for _, package in entries
    )
    assert not ingestion_present


def test_generate_frontend_plugins_omits_a_disabled_plugin():
    entries = generate_frontend_plugins(_lock(disabled_ids={'atlas.apis'}))

    packages = {package for _, package in entries}
    assert '@atlas/plugin-apis' not in packages
    # Other, still-active plugins remain.
    assert '@atlas/plugin-c4' in packages


def test_render_composition_module_omits_a_disabled_plugin_s_import():
    source = render_composition_module(_lock(disabled_ids={'atlas.apis'}))

    assert "from '@atlas/plugin-apis'" not in source
    assert "import { c4Plugin } from '@atlas/plugin-c4'" in source


def test_render_composition_module_imports_every_frontend_plugin_and_core():
    source = render_composition_module(_lock())

    assert "import { apisPlugin } from '@atlas/plugin-apis'" in source
    assert "import { c4Plugin } from '@atlas/plugin-c4'" in source
    assert "import { corePlugin } from './core'" in source
    assert (
        "import { composeFrontendPlugins } from '@atlas/plugin-api'"
        in source
    )
    assert 'export const installedFrontendPlugins = [' in source
    assert '  corePlugin,' in source
    assert 'composeFrontendPlugins(installedFrontendPlugins)' in source


def test_dump_selected_plugins_module_writes_the_rendered_source(tmp_path):
    output = tmp_path / 'selected_plugins.py'

    dump_selected_plugins_module(_lock(), output)

    assert output.read_text() == render_selected_plugins_module(_lock())


def test_dump_composition_module_writes_the_rendered_source(tmp_path):
    output = tmp_path / 'composition.ts'

    dump_composition_module(_lock(), output)

    assert output.read_text() == render_composition_module(_lock())


def _auth_lock() -> Lock:
    base = _lock().model_dump()
    base['auth'] = {
        'providers': [{
            'id': 'atlas.auth.local',
            'owner': 'atlas.catalog',
            'contractVersion': 'atlas.auth.providers.v1',
            'flowKind': 'credentials',
            'remoteLogout': 'unsupported',
            'presentation': {
                'displayName': 'Username and password',
                'credentialFields': [
                    {'id': 'username', 'label': 'Username', 'kind': 'text'},
                    {'id': 'password', 'label': 'Password', 'kind': 'secret'},
                ],
            },
            'signup': 'disabled',
            'principalProvisioning': 'preprovisioned',
            'actorProvisioning': 'manual',
            'profileFields': [],
            'groupSync': {'mode': 'none'},
        }],
        'default': 'atlas.auth.local',
        'publicOrigin': 'https://atlas.example.com',
    }
    return Lock.model_validate(base)


def test_generate_backend_auth_config_contains_core_policy():
    generated = generate_backend_auth_config(_auth_lock())

    assert generated['default'] == 'atlas.auth.local'
    assert generated['sessionMaxAgeSeconds'] == 28800
    assert generated['providers'][0]['principalProvisioning'] == 'preprovisioned'


def test_generate_frontend_auth_bootstrap_contains_presentation_only():
    generated = generate_frontend_auth_bootstrap(_auth_lock())

    assert generated['defaultProviderId'] == 'atlas.auth.local'
    assert generated['providers'][0]['signupOpen'] is False
    rendered = repr(generated)
    assert 'publicOrigin' not in rendered
    assert 'sourceBinding' not in rendered
    assert 'principalProvisioning' not in rendered


def test_rendered_modules_include_auth_configuration():
    backend = render_selected_plugins_module(_auth_lock())
    frontend = render_composition_module(_auth_lock())

    assert 'AUTHENTICATION =' in backend
    assert 'authenticationBootstrap' in frontend
