"""GENERATED by `atlas-compose generate` from atlas.render-demo@2026.09's lock file. Do not edit by hand — regenerate from the manifest/lock instead."""

SELECTED_PLUGINS = (
    "server.apps.catalog.plugin",
    "atlas_plugin_standard_catalog.plugin",
    "atlas_plugin_apis.plugin",
    "atlas_plugin_c4.plugin",
    "atlas_plugin_database_schema.plugin",
    "atlas_plugin_ingestion.plugin",
    "atlas_plugin_flows.plugin",
    "atlas_plugin_search_postgres.plugin",
    "atlas_plugin_search.plugin",
)

DISABLED_PLUGINS = frozenset({})

PLUGIN_CONFIGS = {
    "atlas.c4": {"renderer": "remote", "serverUrl": "https://www.plantuml.com/plantuml"}
}

AUTHENTICATION = {
    "providers": (
        {
            "id": "atlas.auth.local",
            "owner": "atlas.catalog",
            "contractVersion": "atlas.auth.providers.v1",
            "flowKind": "credentials",
            "remoteLogout": "unsupported",
            "presentation": {
                "displayName": "Username and password",
                "credentialFields": (
                    {
                        "id": "username",
                        "label": "Username",
                        "kind": "text",
                        "autocomplete": "username",
                    },
                    {
                        "id": "password",
                        "label": "Password",
                        "kind": "secret",
                        "autocomplete": "current-password",
                    },
                ),
            },
            "signup": "disabled",
            "principalProvisioning": "preprovisioned",
            "actorProvisioning": "manual",
            "profileFields": (),
            "groupSync": {
                "mode": "none",
                "snapshotRequirement": "unsupported",
                "maxAgeSeconds": 28800,
                "mappings": {},
            },
            "restrictedAttributes": (),
            "sourceBinding": None,
        },
    ),
    "default": "atlas.auth.local",
    "sessionMaxAgeSeconds": 28800,
    "publicOrigin": "http://localhost:8000",
    "trustedProxyAddresses": ("127.0.0.1",),
    "adminPassword": {"mode": "disabled", "principalIds": ()},
    "outboundTrust": {"allowedDestinations": (), "allowDevelopmentHttp": False},
    "passwordPolicy": {
        "minimumLength": 15,
        "maximumLength": 128,
        "rejectCommon": True,
        "rejectUserSimilarity": True,
    },
    "recovery": {
        "mode": "operator-managed",
        "verifiedAddressesRequired": True,
        "tokenMaxAgeSeconds": 3600,
    },
}
