# Generated by Django 6.1.1 on 2026-10-04 10:54

from typing import ClassVar

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies: ClassVar[list] = []

    operations: ClassVar[list] = [
        migrations.CreateModel(
            name="SearchIndexEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("document_id", models.CharField(max_length=512, unique=True)),
                ("kind", models.CharField(max_length=128)),
                ("title", models.TextField()),
                ("body", models.TextField(blank=True, default="")),
                ("search_vector", django.contrib.postgres.search.SearchVectorField()),
            ],
            options={
                "indexes": [
                    django.contrib.postgres.indexes.GinIndex(
                        fields=["search_vector"], name="search_pg_vector_gin"
                    )
                ],
            },
        ),
    ]
